ARITHMETIC_BOUNDS_SRCS = \
	abs/abs_signed.c \
	abs/abs_floating.c \
	clamp/clamp_unsigned.c \
	clamp/clamp_signed.c \
	clamp/clamp_floating.c \
	max/max_unsigned.c \
	max/max_signed.c \
	max/max_floating.c \
	min/min_unsigned.c \
	min/min_signed.c \
	min/min_floating.c \
