DATA_STRING_SRCS = \
	adding/append.c \
	adding/insert.c \
	adding/prepend.c \
	cropping/remove_slice.c \
	cropping/select_slice.c \
	positionning/center.c \
	positionning/ljust.c \
	positionning/rjust.c \
	stripping/lstrip.c \
	stripping/remove_prefix.c \
	stripping/remove_suffix.c \
	stripping/rstrip.c \
	stripping/strip.c \
	allocation.c \
	capacity.c \
