DATA_ARRAY_SRCS = \
	creation.c \
	at.c \
	print.c \
	search/contains.c \
	search/find.c \
	search/rfind.c \
	search/count.c \
	search/private.c \
	ordering/min.c \
	ordering/max.c \
	ordering/sort.c \
	ordering/private.c \
