# include src/io/input/Makefile
include src/io/output/Makefile
include src/io/parsing/Makefile
include src/io/printf/Makefile
include src/io/printing/Makefile

IO_SRCS = \
	${addprefix output/,$(IO_OUTPUT_SRCS)} \
	${addprefix parsing/,$(IO_PARSING_SRCS)} \
	${addprefix printf/,$(IO_PRINTF_SRCS)} \
	${addprefix printing/,$(IO_PRINTING_SRCS)} \
	# ${addprefix input/,$(IO_INPUT_SRCS)} \
