include src/data/array/Makefile
include src/data/char/Makefile
include src/data/mem/Makefile
include src/data/str/Makefile
include src/data/string/Makefile
include src/data/vector/Makefile

DATA_SRCS = \
	${addprefix array/,$(DATA_ARRAY_SRCS)} \
	${addprefix char/,$(DATA_CHAR_SRCS)} \
	${addprefix mem/,$(DATA_MEM_SRCS)} \
	${addprefix str/,$(DATA_STR_SRCS)} \
	${addprefix string/,$(DATA_STRING_SRCS)} \
	${addprefix vector/,$(DATA_VECTOR_SRCS)} \
