IO_PRINTF_SRCS = \
	label_printers/bool_label_printer.c \
	label_printers/char_label_printer.c \
	label_printers/prog_label_printer.c \
	label_printers/c_str_label_printer.c \
	label_printers/str_label_printer.c \
	label_printers/signed_label_printer.c \
	label_printers/unsigned_label_printer.c \
	label_printers/floating_label_printer.c \
	label_printers/complex_label_printer.c \
	eprintf.c \
	format_label.c \
	oprintf.c \
	printf.c \
	stderr.c \
	stdout.c \
	str_scanner1.c \
	str_scanner2.c \
