include src/arithmetic/bounds/Makefile
include src/arithmetic/float_math/Makefile

ARITHMETIC_SRCS = \
	${addprefix bounds/,$(ARITHMETIC_BOUNDS_SRCS)} \
	${addprefix float_math/,$(ARITHMETIC_FLOAT_MATH_SRCS)} \
